Add support for V langauge
PrismJS/prism pull request #2687
Opened 2021-01-01 17:16 UTC by taggon

This PR adds support for [the V langauge](https://vlang.io/).

2021-01-02 12:44 UTC, RunDevelopment requested changes
Thank you for making this PR @taggon!

I left you a few comments. Also, directives (e.g. [`#flag linux -lsdl2`](https://github.com/vlang/v/blob/master/doc/docs.md#flag), `#include "sqlite3.h"`) and [nested multiline comments](https://github.com/vlang/v/blob/master/doc/docs.md#comments) are not supported. Please add them. 

Apart from that, very solid work. Thank you!

2021-01-07 12:36 UTC, taggon commented
@RunDevelopment Thanks. I fixed all the problems you mentioned and also add support for directives(such as `#include` and `#flag`).

2021-01-07 16:58 UTC, RunDevelopment requested changes
Thank you for your work! 

I'm sorry but one of my suggestions contained faulty code. My comment contains more information and a fix.

2021-01-07 16:58 UTC, RunDevelopment commented on components/prism-v.js
> +							inside: Prism.languages.v
I'm sorry that I suggested code that doesn't work. `Prism.languages.v` isn't defined yet, so `inside` will be set to `undefined`.

To fix this, please replace this line with:
```suggestion
							inside: null // see below
```

And add the following line after the `Prism.languages.extend` call.

```js
Prism.languages.v['string'][1].inside['interpolation'].inside['interpolation-expression'].inside = Prism.languages.v;
```

2021-01-08 13:22 UTC, RunDevelopment approved these changes

2021-01-08 13:22 UTC, merged

2021-01-08 13:23 UTC, RunDevelopment commented
Thank you for contributing @taggon!