Add KuMir
PrismJS/prism pull request #2760
Opened 2021-02-12 20:13 UTC by edukisto

Resolves #2759.

2021-02-12 20:16 UTC, RunDevelopment commented
Oh oh. Sorry @edukisto. It's my fault CI fails. I'll try to fix it immediately.

2021-02-12 20:32 UTC, RunDevelopment commented
@edukisto I fixed it now. Please rebase and then the CI should pass. I'm sorry for the inconvenience.

2021-02-12 22:32 UTC, RunDevelopment requested changes
Excellent work @edukisto!

I only have a few nits and then we can merge this.

I also thoroughly enjoyed reading through #2759. Thank you for the detailed explanation of a language that otherwise has little English documentation.

2021-02-12 23:47 UTC, edukisto commented on components/prism-kumir.js
> +			// pattern: /(["'])[^\\1\n\r]*?\1/, // 5-10% slower!
Thank you!

The saddest thing is that I’ve tested three correct templates, but haven’t fix the comment.

Both `/(["'])(?:(?!\1)[^\n\r])*\1/` and `/(["'])[^\n\r]*?\1/` are slower than `/"[^\n\r"]*"|'[^\n\r']*'/`.

2021-02-13 00:38 UTC, edukisto commented on components/prism-kumir.js
> +				alias: 'inserted'
Maybe, `important`?

2021-02-13 00:38 UTC, edukisto commented on components/prism-kumir.js
> +	 * @param {String} flags The regular expression flags.
Thanks!

2021-02-13 14:13 UTC, RunDevelopment approved these changes

2021-02-13 14:14 UTC, merged

2021-02-13 14:14 UTC, RunDevelopment commented
Thank you very much for contributing @edukisto!