Added support for CFScript
PrismJS/prism pull request #2771
Opened 2021-02-18 19:16 UTC by mjclemente

This partially deals with #2035, though does not resolve it entirely.

CFML has independent tag and script based syntaxes. This adds support for script syntax.

Here are some language references:

- https://cfdocs.org/script
- https://helpx.adobe.com/coldfusion/developing-applications/the-cfml-programming-language/extending-coldfusion-pages-with-cfml-scripting/the-cfscript-language.html
- https://www.petefreitag.com/cheatsheets/coldfusion/cfscript/

2021-02-19 13:00 UTC, RunDevelopment requested changes
Good work @mjclemente!

A couple of minor things and then this is ready.

2021-02-19 14:39 UTC, mjclemente commented
Thanks for the fast, thorough, and really helpful review 😀 

I believe I've made all requested changes.

2021-02-19 14:50 UTC, RunDevelopment requested changes
Thank you for the quick response!

One more comment. Also, could you please add the link to https://cfdocs.org/script in a comment at the beginning of the file? This will be helpful to future contributors.

2021-02-19 14:50 UTC, RunDevelopment commented on components.json
> +			"title": "CFML Script",
The docs consistently call this langauge "CFScript". I think we should too.
```suggestion
			"title": "CFScript",
```

2021-02-19 15:23 UTC, mjclemente commented
Makes sense!

Changes made. Again, thanks for the prompt and thorough handling!

2021-02-19 16:11 UTC, RunDevelopment approved these changes

2021-02-19 16:11 UTC, merged

2021-02-19 16:12 UTC, RunDevelopment commented
Thank you for contributing @mjclemente!

2021-02-19 16:13 UTC, mjclemente commented
Thank you! 🎉

2025-09-07 07:38 UTC, dawesi commented
can we also create a branch of cfml for cfml/lucee (which boxlang also supports that syntax)

This is divergent from Adobe CFML/CFScript now also, as it containers many functions / helpers methods that are not in coldfusion and vice versa.

They publish the latest docs in json files zipped here.

https://docs.lucee.org/lucee-docs-json.zip

2025-10-01 21:57 UTC, mjclemente commented
Given that Lucee/Boxlang/Adobe ColdFusion are all CFML, my first thought would be that they could all be incorporated here. While there may be some different tags, I don't see any issues in including them all - they have more in common than different (at least Lucee CFML and Adobe). Not sure what functions are missing at this point.