Add support for @propertyWrapper, @MainActor, @globalActor
PrismJS/prism pull request #3009
Opened 2021-07-24 07:46 UTC by AvdLee

New types that didn't exist in Prism yet, but we need them! 🎉

2021-07-24 10:33 UTC, RunDevelopment requested changes
One minor nit. Apart from that it's gtg. Thank you @AvdLee!

2021-07-24 10:33 UTC, RunDevelopment commented on components/prism-swift.js
> +	'atrule': /@\b(?:IB(?:Outlet|Designable|Action|Inspectable)|class_protocol|exported|globalActor|noreturn|NS(?:Copying|Managed)|MainActor|objc|propertyWrapper|UIApplicationMain|auto_closure)\b/,
M < N

```suggestion
	'atrule': /@\b(?:IB(?:Outlet|Designable|Action|Inspectable)|class_protocol|exported|globalActor|MainActor|noreturn|NS(?:Copying|Managed)|objc|propertyWrapper|UIApplicationMain|auto_closure)\b/,
```

2021-07-24 10:36 UTC, RunDevelopment commented
Also, please use backticks around `@propertyWrapper` (and others) in commit messages, comments, and titles. Otherwise, GitHub will ping these people. Let's try to not annoy them :)

2021-07-26 07:39 UTC, AvdLee commented
> Also, please use backticks around @propertyWrapper (and others) in commit messages, comments, and titles. Otherwise, GitHub will ping these people. Let's try to not annoy them :)

Oh, oops! didn't think about that!

2021-07-26 09:54 UTC, RunDevelopment commented
The build still fails. Could you please rebuild Prism?

2021-07-26 10:08 UTC, AvdLee commented
> The build still fails. Could you please rebuild Prism?

I've never done that before, my previous PR succeeded as well w/o rebuilding Prism 🤔 
Is there any guidance for this? I'm not really experienced in deploying such packages

2021-07-26 11:14 UTC, RunDevelopment commented
Just run `npm ci && npm run build` and commit the changes.

2021-07-26 11:21 UTC, AvdLee commented
Thanks, that was actually easy. Pushed the changes, let's see if CI is happy now!

2021-07-26 11:50 UTC, merged

2021-07-26 11:50 UTC, RunDevelopment commented
Thank you for contributing @AvdLee!