Document disableWorkerMessageHandler
PrismJS/prism pull request #3088
Opened 2021-09-20 13:56 UTC by jakearchibald

2021-09-20 14:39 UTC, RunDevelopment commented
I didn't even know we had this option. Thank you for documenting it!

Unfortunately, you documented the wrong file. `prism.js` is generated. Please document `components/prism-core.js` instead, run `npm ci && npm run build`, and commit all changes.

2021-09-20 14:48 UTC, jakearchibald commented
Done!

2021-09-23 11:37 UTC, RunDevelopment requested changes
Sorry for the delay @jakearchibald!

2021-09-23 11:37 UTC, RunDevelopment commented on components/prism-core.js
> +		 * By default, if Prism is in a web worker, it assumes its in a worker it created itself, so it uses
```suggestion
		 * By default, if Prism is in a web worker, it assumes that it is in a worker it created itself, so it uses
```

2021-09-23 12:06 UTC, jakearchibald commented
Updated

2021-09-23 13:24 UTC, RunDevelopment commented on components/prism-core.js
> +		 *
Our linter really doesn't like trailing spaces.
```suggestion
		 *
```

2021-09-23 14:59 UTC, jakearchibald commented
Fixed

2021-09-23 15:33 UTC, RunDevelopment approved these changes

2021-09-23 15:33 UTC, merged

2021-09-23 15:33 UTC, RunDevelopment commented
Thank you for contributing @jakearchibald!