Add support for METAFONT
PrismJS/prism pull request #3465
Opened 2022-06-05 02:05 UTC by LaeriExNihilo

Includes support for Donald Knuth's historic language for fontdesigning and fontmaking. While this language is outdated in many regards its legacy endures in METAPOST and PGF/TikZ, and its macro core principle has real depth. May be of use for people exploring the inception of the TeX ecosystem.

2022-06-06 09:16 UTC, RunDevelopment requested changes
Thank you for the PR @LaeriExNihilo!

The language itself looks good, but there aren't enough tests, so our regex coverage fails. You can see the untested regexes/alternatives [here](https://github.com/PrismJS/prism/runs/6752912791?check_suite_focus=true#step:5:1267) or by running `npm run regex-coverage`.

2022-06-06 09:16 UTC, RunDevelopment commented on components/prism-metafont.js
> +Prism.languages.mf=Prism.languages['metafont'];
Could you please remove the alias (here and in `components.json`)?

Short aliases are limited resource, and I don't like the idea of `mf` being taken by a language that basically isn't used anymore.

2022-06-06 20:20 UTC, LaeriExNihilo commented
This should pass now @RunDevelopment . While doing the tests I also found a few mistakes in my definitions so it was a good opportunity.

2022-06-06 20:23 UTC, RunDevelopment commented
Thanks @LaeriExNihilo! I forgot to mention that we also have ESLint. Please run `npm run lint:fix` to fix (hopefully) all linting errors.

2022-06-06 21:05 UTC, LaeriExNihilo commented
lint is complaining about a duplicate for my operators but I can't seem to find it. I fixed the spacing (that VSCode had by default to spaces instead of tabs) but I'm not sure it will fix it.

2022-06-06 21:35 UTC, LaeriExNihilo commented
Locally this build passes all tests. lint fixed some alphabetical misorderings I hadn't seen.

2022-06-07 07:35 UTC, merged

2022-06-07 07:35 UTC, RunDevelopment commented
Thank you for contributing @LaeriExNihilo!